[package]
name = "zcashd-rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.74"
rest-json-client = "0.2.1"
tower = "0.4.13"
