[package]
name = "zcashd-rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.74"
jsonrpc = { version = "0.16.0", features = ["simple_http"] }
tower = "0.4.13"
