[package]
name = "zcashd-rpc-fuzzer"
version = "0.1.0"
edition.workspace = true

[dependencies]
async-trait.workspace = true
derive_more.workspace = true
rand_chacha.workspace = true
rand.workspace = true
serde_json.workspace = true
serde.workspace = true
zcashd-rpc.workspace = true
