[package]
name = "zcashd-process"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow.workspace = true
getset.workspace = true
tempdir.workspace = true
tokio = { workspace = true, features = ["process"] }
